### ISSUE TITLE
👀👀

### ISSUE THREAD

**Issue by l3773l** [ll06printf/ll06printf#1]
你好👋

**Comment by ll06printf** [comment]
Github以用户名命名的仓库的README会显示在用户信息页中。👀

**Comment by l3773l** [comment]
👀



---Original---
From: ***@***.***&gt;
Date: Sun, Jun 2, 2024 20:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ll06printf/ll06printf] 👀👀 (Issue #1)




 
Github以用户名命名的仓库的README会显示在用户信息页中。👀
